spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  application:
    name: route-microservice
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        health-check-tls-skip-verify: true
        health-check-url: https://localhost:${server.port}/actuator/health

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  ssl:
    key-store: ***
    key-store-password: ***
    key-store-type: ***
    key-alias: ***
